#!/usr/bin/env python3
"""Render README.md from data/*.json (called by scripts/build.py).

README.md is generated: edit data/*.json or this template, then rebuild.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import jevlib as J  # noqa: E402

AVAIL_MD = {'available': '●', 'partial': '◐', 'restricted': '◑', 'project_page_only': '◔', 'claimed_not_located': '○ claimed',
            'not_located': '○', 'not_applicable': '–', 'not_assessed': '·', 'not_attempted': '·', 'no': '○'}


def md(s):
    return (s or '').replace('|', '\\|').replace('\n', ' ')


def main():
    d = J.load_all()
    s = J.compute_stats(d)
    cfg = d['config']
    tax = d['taxonomy']
    P = d['papers']['papers']
    C = J.by_id(d['claims']['claims'])
    T = {k: J.by_id(tax[k]) for k in ('topics', 'test_levels', 'model_relationships', 'background_groups', 'repository_types', 'method_families')}
    site = J.safe_url(cfg.get('site_url'))
    repo = J.safe_url(cfg.get('repository_url'))
    L = []
    a = L.append
    a('<!-- Generated by scripts/render-readme.py from data/*.json. Edit the data, then run `python3 scripts/build.py`. -->')
    a('')
    a('# Awesome Jev')
    a('')
    a('**An evidence survey of TypeSafe’s Jev and Jev-like typed decision models — calibration, selective control and open implementations.**')
    a('')
    if site:
        a(f'**Website:** <{site}>')
    else:
        a('**Website:** open `index.html` in a browser, or serve the folder with `python3 -m http.server`.')
    a('')
    authors = [x for x in cfg.get('authors') or [] if x.get('name')]
    if authors:
        a('**Author:** ' + ', '.join(f'[{x["name"]}]({J.safe_url(x.get("url"))})' if J.safe_url(x.get('url')) else x['name'] for x in authors))
        a('')
    a('> Numbers are as reported by paper authors, the vendor or repository maintainers; nothing here is a unified leaderboard.')
    a('')
    a('## Contents')
    a('')
    for h in ['Findings', 'Core studies', 'Peripheral study', 'Open implementations and evaluations', 'Background references',
              'Related survey', 'Method', 'Contributing', 'Citation and licence']:
        a(f'- [{h}](#{h.lower().replace(" ", "-")})')
    a('')
    a('## Findings')
    a('')
    for f in tax['findings']:
        a(f'**{f["id"]} · {f["title"]}** {f["body"]}')
        a('')
    a('## Core studies')
    a('')
    a('| Date (v1) | Study | Relationship to Jev | Test level | Headline (author-reported) | Code |')
    a('| --- | --- | --- | --- | --- | --- |')
    for p in sorted([p for p in P if p['tier'] == 'core'], key=lambda p: p['published_at'], reverse=True):
        head = C[p['claims'][0]]['headline'] if p['claims'] else ''
        code = p['openness']['code']
        code_md = f'[{AVAIL_MD[code["status"]]}]({code["url"]})' if code.get('url') else AVAIL_MD[code['status']]
        fam = ' ¹' if p.get('study_family_id') else ''
        a(f'| {p["published_at"][:10]} | [{md(p["title"])}]({p["url"]}){fam} | {md(p["relationship"])} | {T["test_levels"][p["test_level"]]["label"]} | {md(head)} | {code_md} |')
    a('')
    a('¹ Same study family (shared authors and service path); not independent replications. Code: ● available · ◐ partial · ◔ project page only · ○ not located · “claimed” = the paper says it is released.')
    a('')
    a('## Peripheral study')
    a('')
    for p in [p for p in P if p['tier'] == 'peripheral']:
        a(f'- [{md(p["title"])}]({p["url"]}) — {md(p["relationship"])} {md(p["caveats"][0])}')
    a('')
    a('## Open implementations and evaluations')
    a('')
    a('● available · ◐ partial · ◑ restricted · ◔ project page only · ○ not located · – not applicable')
    a('')
    a('| Resource | Type | Family | Code | Weights | Training | Evaluation | Raw predictions |')
    a('| --- | --- | --- | :-: | :-: | :-: | :-: | :-: |')
    for r in sorted([r for r in d['repositories']['repositories'] if 'priority' in r['sets']], key=lambda r: (r['type'], r['full_name'].lower())):
        av = r['availability']
        fam = T['method_families'][r['method_family']]['label'] if r.get('method_family') else '—'
        a(f'| [{r["full_name"]}]({r.get("readme_url") or r["url"]}) | {T["repository_types"][r["type"]]["label"]} | {fam} | '
          + ' | '.join(AVAIL_MD.get(av.get(k, 'not_assessed'), '·') for k in ('code', 'weights', 'training_code', 'evaluation', 'raw_predictions')) + ' |')
    a('')
    a('## Background references')
    a('')
    for g in tax['background_groups']:
        items = [p for p in P if p['tier'] == 'background' and p['background_group'] == g['id']]
        if not items:
            continue
        a(f'### {g["label"]}')
        a('')
        for p in sorted(items, key=lambda p: p['published_at'], reverse=True):
            venue = f' · {p["venue"]}' if p['venue_source'] in ('arxiv_comment', 'arxiv_journal_ref') else ''
            a(f'- [{md(p["title"])}]({p["url"]}) ({p["year"]}{venue}) — {md(p["role"])}')
        a('')
    a('## Related survey')
    a('')
    for rs in d['review-relations']['related_surveys']:
        if rs['id'].startswith('gh:'):
            a(f'[*Decisions, Not Tokens*]({rs["url"]}) (working draft, 2026) covers machine-native decision models more broadly, from classical classifiers to Jev.')
        else:
            a(f'[*{md(rs["title"])}*]({rs["url"]}) (arXiv preprint, 2026) {md(rs["description"])}')
        a('')
    a('## Method')
    a('')
    a('- Scope, search and screening: [docs/methodology.md](docs/methodology.md). Limitations: [docs/limitations.md](docs/limitations.md).')
    a('- How evidence records and openness fields are defined: [docs/evidence-audit.md](docs/evidence-audit.md).')
    a('- Survey manuscript: [PDF](paper/main.pdf) · [Markdown](paper/survey.md).')
    a('- Data: [`data/`](data/) (JSON records), [`data/exports/`](data/exports/) (CSV) and [`data/references.bib`](data/references.bib).')
    a('')
    a('## Contributing')
    a('')
    a('New studies, corrections, code or weights updates and reproduction reports are welcome — see [CONTRIBUTING.md](CONTRIBUTING.md)'
      + (f' or [open an issue]({repo.rstrip("/")}/issues/new/choose).' if repo else '.'))
    a('')
    a('## Citation and licence')
    a('')
    a('Citation metadata is in [CITATION.cff](CITATION.cff) (GitHub shows it under “Cite this repository”).')
    a('')
    if authors:
        first = authors[0]
        names = ' and '.join(f'{x.get("family_names") or x["name"]}, {x.get("given_names") or ""}'.rstrip(', ') for x in authors)
        key = (first.get('family_names') or first['name'].split()[-1]).lower() + s['cutoff'][:4] + 'jevsurvey'
        a('```bibtex')
        a(f'@misc{{{key},')
        a(f'  author       = {{{names}}},')
        a('  title        = {Jev and Typed Decision Models: An Empirical Survey of Calibration, Selective Control, and Open Implementations},')
        a(f'  year         = {{{s["cutoff"][:4]}}},')
        if repo:
            a(f'  howpublished = {{\\url{{{repo}}}}},')
        a(f'  note         = {{Version {J.VERSION}, data cutoff {J.fmt_date(s["cutoff"])}. Working draft, not peer-reviewed}}')
        a('}')
        a('```')
        a('')
    a('Licences: the code (scripts, site, tests, workflows) is under the [MIT License](LICENSE); original text, figures and curated data are under '
      '[CC BY 4.0](LICENSE-CONTENT.md). Third-party material — paper metadata, quoted README facts, vendor documentation — keeps its own terms; '
      'see [NOTICE.md](NOTICE.md).')
    a('')
    (J.ROOT / 'README.md').write_text('\n'.join(L), encoding='utf-8')


if __name__ == '__main__':
    main()
