#!/usr/bin/env python3
"""Render the data-bearing documentation from data/*.json (called by scripts/build.py).

Generates docs/methodology.md, docs/evidence-audit.md and data/README.md.
The hand-written docs/limitations.md is not touched.
"""
import pathlib
import sys
from collections import Counter

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import jevlib as J  # noqa: E402

GEN = '<!-- Generated by scripts/render-docs.py from data/*.json. Edit the data or the script, then run scripts/build.py. -->\n\n'


def md(s):
    return (s or '').replace('|', '\\|').replace('\n', ' ')


def methodology(d, s):
    runs = J.by_id(d['search-runs']['runs'])
    snap, inc, rej = runs['snapshot-arxiv-2026-09-23'], runs['increment-arxiv-2026-09-23T0818Z'], runs['snapshot-arxiv-rejected']
    gh, ghi = runs['snapshot-github-2026-09-23'], next((r for r in d['search-runs']['runs'] if r['id'].startswith('increment-github')), None)
    L = [GEN, '# Methodology', '',
         f'Data cutoff: **{J.fmt_date(s["cutoff"])}** (Asia/Singapore). This document is generated from `data/search-runs.json`, `data/papers.json` and `data/claims.json`.', '',
         '## 1. Questions', '',
         'RQ1 definition and lineage · RQ2 probability quality · RQ3 efficiency attribution · RQ4 selective control · RQ5 robustness · RQ6 openness and reproducibility (see `paper/survey.md` §1).', '',
         '## 2. Search', '',
         f'**Snapshot (2026-09-23).** {snap["accepted_queries"]} accepted arXiv API queries returned {snap["hits_before_dedup"]} hits and {snap["unique_screened"]} unique records after de-duplication by unversioned arXiv ID. '
         f'One compound query reported {rej["reported_total"]:,} results, was stopped after HTTP 429 and was rejected rather than screened; it was replaced by four narrow title/abstract queries. '
         '`all:` searches arXiv metadata fields, not PDF full text, so a broader recent “decision model” query was added and found a core paper that brand-name queries missed.', '',
         '| ID | Query | Hits |', '| --- | --- | ---: |']
    L += [f'| `{q["id"]}` | `{md(q["query"])}` | {q["total"] if q["total"] is not None else "—"} |' for q in snap['queries']]
    L += ['', 'Background references came partly from these queries and partly from a purposive seed set retrieved by explicit arXiv ID (not a discovery count).', '',
          f'**Same-day increment ({inc["id"].split("-", 2)[-1]}).** All {inc["accepted_rerun"]["queries"]} accepted queries were re-run; totals were '
          f'{"identical" if inc["accepted_rerun"]["reproduced_snapshot_totals"] else "different"} ({inc["accepted_rerun"]["hits_before_dedup"]} hits). '
          f'{len(inc["expansion"])} expansion queries widened the vocabulary beyond the brand name; queries returning more than 2,000 results were rejected by rule (the arXiv API treats hyphenated and multi-word phrases loosely). '
          f'All 58 bibliography IDs were refreshed: no new versions, titles or journal references.', '',
          '| ID | Query | Hits | Status |', '| --- | --- | ---: | --- |']
    L += [f'| `{q["id"]}` | `{md(q["query"])}` | {q["total"]} | {q["status"]} |' for q in inc['expansion']]
    dec = inc['decisions']
    L += ['', f'Of {inc["new_candidates"]} new records, {dec.get("include_background", 0)} were added as background references and '
          f'{dec.get("outside_core_scope", 0) + dec.get("outside_core_scope_linked_dataset", 0)} were excluded with a recorded reason '
          '(`research/screening.json`).', '',
          f'**GitHub.** Five repository searches produced {gh["unique_results"]:,} unique discovery results at the snapshot; {gh["catalogues_audited"]} catalogues/guides were audited ({gh["readmes_fetched"]} READMEs at pinned commits) and {gh["priority_resources"]} priority implementation and evaluation resources were read (2 overlap). '
          f'README outgoing links ({gh["outgoing_candidates_all"]:,}) are unverified candidates and are never counted as projects.']
    if ghi:
        L += [f'The increment re-ran the searches: {ghi["unique_results"]:,} results, {ghi["new_unverified_candidates"]} new unverified candidates (none added). Watched repositories: ' +
              '; '.join(f'`{w["repo"]}` head `{w.get("head", "?")[:10]}`' for w in ghi['watched']) + '.']
    for run in d['search-runs']['runs']:
        if run['kind'] != 'arxiv_keyword_increment' or run['id'] == inc['id']:
            continue
        dd = run['decisions']
        L += ['', f'**Increment {run["id"].split("-", 2)[-1]}.** {run["accepted_rerun"]["queries"]} accepted and {len(run["expansion"])} expansion queries; '
              f'{run["new_candidates"]} records not screened before: {dd.get("include_core", 0)} added as core studies, {dd.get("include_background", 0)} as background, '
              f'{dd.get("excluded", dd.get("outside_core_scope", 0))} excluded with a recorded reason. {run.get("note") or ""}'.rstrip()]
    L += ['', '**Curated lists (2026-10-06).** Repositories listed in OmniJev/awesome-jev-gallery and papers listed in OmniJev/awesome-jev-papers were checked against their own README or paper before inclusion; '
          'decisions and reasons are in `research/repository-screening.json`. Lineage items in those lists that are general infrastructure were kept as context and covered through their papers.']
    L += ['', '## 3. Eligibility', '',
          '- **Core:** evaluates TypeSafe Jev, a clearly identified Jev-like typed-decision implementation, or a system whose contribution materially depends on such decisions.',
          '- **Peripheral:** within reach of the scope but with contested or self-reported claims; kept visible, not pooled.',
          '- **Background:** adjacent methods needed for theory and baselines (classification, calibration, selective prediction, decision-focused calibration, structured output, judging, routing, label robustness), related reviews, and earlier work the interface descends from, each with a stated role.',
          '- **Excluded:** name collisions (Japanese encephalitis, JEPA, unrelated TypeSafe/Scala, other RLCD expansions), generic System 1/2 work without a typed-decision link.', '',
          '## 4. Screening and reading depth', '',
          '- Core and peripheral studies: full text, key tables and limitation sections; every extracted number carries a locator. When a study posts a new arXiv version, the new version is re-read and its records updated.',
          '- Background references: arXiv metadata and abstract (one reranker paper spot-checked in full text).',
          '- Repositories: README and metadata at a pinned commit, with selected source files for a few; code, weights and data links are checked to resolve; nothing is executed.',
          '- One AI-assisted reviewer. This is not a registered protocol or a PRISMA-compliant systematic review; a second independent screener is the first open task (docs/limitations.md).', '',
          '## 5. Extraction', '',
          'Each checkable statement is an evidence record in `data/claims.json`, typed as an author-reported experiment, vendor documentation, a vendor-reported result or a community report. '
          'Fields: subject, claim text, headline, source URL and locator, evidence type, metric/value/unit, baseline, task, sample size (or a reason), model and version (or a reason), hardware, test level, measurement scope, limitations and links to findings F1–F10.', '',
          'Measurement scopes are never pooled: single request, amortized per question, batch, end to end, simulation, author estimate, vendor claim. Test levels: model test, system test, hybrid, simulation.', '',
          'Openness is recorded as six independent fields per paper — code, weights, data, raw predictions, recomputable, independently reproduced — and seven per repository. “Not located” means not found, not that it does not exist.', '',
          '## 6. Synthesis', '',
          'Findings are stated at the strength their records allow, with supporting and qualifying records listed together (site §04, `paper/survey.md` §7). Study families are synthesised once. No meta-analytic pooling is attempted: tasks, metrics and scopes are heterogeneous.', '',
          '## 7. Updating', '',
          '1. `python3 scripts/update-metadata.py` and `python3 scripts/update-github.py` write a dated working folder under `research/increments/` (not committed) listing records not yet screened.',
          '2. Screen the new candidates, add each decision and reason to `research/screening.json` (and seen repositories to `research/github-seen.json`), add included records to `data/`, and log the run in `data/search-runs.json`.',
          '3. `python3 scripts/validate-data.py && python3 scripts/build.py`, update `CHANGELOG.md`, and re-run `python3 scripts/check-links.py`.', '']
    return '\n'.join(L)


def audit(d, s):
    P = [p for p in d['papers']['papers'] if p['tier'] in ('core', 'peripheral')]
    C = J.by_id(d['claims']['claims'])
    tax = d['taxonomy']
    TL = J.by_id(tax['test_levels'])
    L = [GEN, '# Evidence audit', '',
         'Rules used to read and record evidence, followed by the per-study audit. Values are as reported by their sources; none were re-run.', '',
         '## Rules', '',
         '- Product, paradigm and system are separate objects: hosted TypeSafe Jev; Jev-like models, readouts and adapters; systems that use typed decisions.',
         '- Type validity, semantic correctness, calibration and downstream utility are evaluated separately.',
         '- A number is only comparable with another from the same measurement scope, task and protocol.',
         '- Same authors, shared data or the same base model do not make two results independent; study families are synthesised once.',
         '- Code visible, weights available, data available, raw predictions available, recomputable and independently reproduced are separate fields.',
         '- Where raw data are unavailable, experiments are listed as *proposed*; no result tables or intervals are generated.', '',
         '## Per-study profile', '',
         '| Study (v1 date) | Relationship | Test level | Model version | Code | Weights | Data | Predictions | Records |',
         '| --- | --- | --- | --- | --- | --- | --- | --- | ---: |']
    for p in sorted(P, key=lambda p: p['published_at']):
        mv = '; '.join(f'{v["model"]}: {v.get("version") or "not reported"}' for v in p['model_versions'])
        o = p['openness']
        L.append(f'| [{md(p["short_title"])}]({p["url"]}) ({p["published_at"][:10]}){" ¹" if p.get("study_family_id") else ""} | {md(", ".join(p["model_relationship"]))} | '
                 f'{TL[p["test_level"]]["label"]} | {md(mv)} | {o["code"]["status"]} | {o["weights"]["status"]} | {o["data"]["status"]} | {o["predictions"]["status"]} | {len(p["claims"])} |')
    fams = [r for r in d['review-relations']['relations'] if r['type'] == 'study_family']
    L += ['', '¹ Member of a study family: ' + '; '.join(f'`{r["id"]}` (' + ', '.join(m.split(':', 1)[1] for m in r['members']) + ')' for r in fams) + '.', '',
          '## Measurement scopes of speed and cost figures', '']
    for scope in ('single_request', 'amortized_question', 'batch', 'end_to_end', 'simulation', 'author_estimate', 'vendor_claim'):
        rows = [c for c in d['claims']['claims'] if c['measurement_scope'] == scope]
        if rows:
            L.append(f'**{scope.replace("_", " ")}** — ' + '; '.join(f'{md(c["headline"])} ({c["subject"].split(":", 1)[-1]})' for c in rows))
            L.append('')
    L += ['## What would upgrade the evidence', '',
          '1. Version-pinned reruns of the option-binding, rejection and calibration results on hosted Jev with a test–retest floor.',
          '2. Same-protocol comparisons of hosted Jev, open decision models, frozen readouts and structured-output LLMs, with held-out thresholds (paper §10).',
          '3. Independent replications across author groups, starting with the study families flagged above.',
          '4. Public raw predictions for studies that report results without releasing them.', '']
    return '\n'.join(L)


def data_readme(d, s):
    return '\n'.join([GEN, '# Data', '',
        f'Canonical records for the Jev survey (updated {s["cutoff"]}). Edit these files, then run `python3 scripts/build.py`.', '',
        '| File | Contents | Edited by hand? |', '| --- | --- | --- |',
        '| `papers.json` | core, peripheral and background records with verified arXiv metadata, editorial fields, openness and locators | yes |',
        '| `claims.json` | evidence records from papers, vendor pages and community repositories | yes |',
        '| `repositories.json` | open models, benchmarks, applications, tools and catalogues, each audited at a linked commit | yes |',
        '| `taxonomy.json` | vocabularies: stages, method families, topics, applications, relationships, test levels, scopes, evidence types, openness statuses, ecosystem roles, findings, failure modes, application cards | yes |',
        '| `review-relations.json` | study families, lineage, name collisions, related reviews and catalogues | yes |',
        '| `sources.json` | official vendor pages used as sources | yes |',
        '| `search-runs.json` | arXiv and GitHub search runs (snapshot and increments) | appended per increment |',
        '| `references.bib`, `exports/*.csv` | generated | no |', '',
        'Screening decisions for every arXiv record considered, the repositories checked from curated lists, and the GitHub repositories already seen are in `../research/`.', '',
        '## Key rules', '',
        '- IDs: `arxiv:<id>` for papers, `gh:<owner/name>` (lower case) for repositories, `c-…`, `v-…`, `r-…` for claims from papers, vendor pages and repositories.',
        '- Unknown values are `null` with a `reason`; `null` is never zero.',
        '- Multi-label fields (`topics`, `stages`, `method_families`, `model_relationship`) may overlap.',
        '- Venues are recorded only as stated in arXiv metadata (`venue_source`); `venue_verified_at` stays null until checked against proceedings.',
        '- CSV exports prefix cells that start with `= + - @`, tab or CR with an apostrophe (formula-injection guard).', ''])


def main():
    d = J.load_all()
    s = J.compute_stats(d)
    docs = J.ROOT / 'docs'
    docs.mkdir(exist_ok=True)
    (docs / 'methodology.md').write_text(methodology(d, s), encoding='utf-8')
    (docs / 'evidence-audit.md').write_text(audit(d, s), encoding='utf-8')
    (J.ROOT / 'data' / 'README.md').write_text(data_readme(d, s), encoding='utf-8')


if __name__ == '__main__':
    main()
