#!/usr/bin/env python3
"""Render README.md from data/*.json (called by scripts/build.py).

README.md is generated: edit data/*.json or this template, then rebuild.
"""
import pathlib
import sys
from collections import defaultdict
from urllib.parse import quote

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import jevlib as J  # noqa: E402

AVAIL_MD = {'available': '●', 'partial': '◐', 'restricted': '◑', 'project_page_only': '◔', 'claimed_not_located': '○ claimed',
            'not_located': '○', 'not_applicable': '–', 'not_assessed': '·', 'not_attempted': '·', 'no': '○'}
GROUPS = [('commercial_jev', 'Studies of hosted Jev'), ('independent_jev_like', 'Open and independent Jev-like models'),
          ('downstream_system', 'Systems built on typed decisions')]
# README artwork lives in assets/readme/ (static SVGs); each card links to the section heading of the same name.
ICON = {'About the survey': 'about', 'Repository guide': 'guide', 'Findings': 'findings', 'Studies of hosted Jev': 'hosted',
        'Open and independent Jev-like models': 'open', 'Systems built on typed decisions': 'systems', 'Peripheral study': 'peripheral',
        'Open ecosystem': 'ecosystem', 'Background references': 'background', 'Related reviews and catalogues': 'related',
        'Method': 'method', 'Contributing': 'contribute', 'Star history': 'star', 'Citation and licence': 'cite'}
CARDS = [('findings', 'Findings', 'Cross-study syntheses'), ('hosted', 'Studies of hosted Jev', 'Studies of TypeSafe’s model'),
         ('open', 'Open and independent Jev-like models', 'Same shape, other mechanisms'),
         ('systems', 'Systems built on typed decisions', 'Built on typed decisions'),
         ('ecosystem', 'Open ecosystem', 'Models, benchmarks and tools'), ('background', 'Background references', 'Calibration, deferral, routing')]
ISSUE_FORMS = [('add-paper.yml', 'Suggest a study'), ('correction.yml', 'Correct a record'), ('reproduction.yml', 'Report a reproduction'),
               ('resource-update.yml', 'Update code, weights or availability')]


def md(s):
    return (s or '').replace('|', '\\|').replace('\n', ' ')


def anchor(h):
    return ''.join(c for c in h.lower().replace(' ', '-') if c.isalnum() or c == '-')


def badge(label, message, color, alt, href=None, logo=None):
    esc = lambda t: quote(t.replace('-', '--').replace('_', '__'), safe='')  # noqa: E731 - shields.io path escaping
    src = f'https://img.shields.io/badge/{esc(label)}-{esc(message)}-{color}?style=flat-square' + (f'&logo={logo}&logoColor=white' if logo else '')
    img = f'<img src="{src}" alt="{alt}">'
    return f'  <a href="{href}">{img}</a>' if href else f'  {img}'


def main():
    d = J.load_all()
    s = J.compute_stats(d)
    cfg = d['config']
    tax = d['taxonomy']
    P = d['papers']['papers']
    C = J.by_id(d['claims']['claims'])
    R = d['repositories']['repositories']
    T = {k: J.by_id(tax[k]) for k in ('topics', 'test_levels', 'model_relationships', 'background_groups', 'repository_types', 'method_families', 'applications', 'ecosystem_roles')}
    site = J.safe_url(cfg.get('site_url'))
    repo = J.safe_url(cfg.get('repository_url'))
    L = []
    a = L.append

    def heading(title):
        a(f'<img src="assets/readme/section-icons/{ICON[title]}.svg" alt="" width="36" align="left">')
        a('')
        a(f'## {title}')
        a('')

    a('<!-- Generated by scripts/render-readme.py from data/*.json. Edit the data, then run `python3 scripts/build.py`. -->')
    a('')
    a('<div align="center">')
    banner = ('<img src="assets/readme/hero-banner.svg" width="1000" alt="Awesome Jev — an evidence survey of Jev and typed decision models. '
              'Every answer type-checks. The evidence decides the rest.">')
    a(f'  <a href="{site}">{banner}</a>' if site else f'  {banner}')
    a('')
    a('  <p><strong><em>⭐ Star us if you find this useful!</em></strong></p>')
    a('')
    if site:
        a(badge('explore', 'project website', '3a45c8', 'Explore the project website', site))
    a(badge('survey', 'PDF', 'B31B1B', 'Read the survey (PDF)', 'paper/main.pdf', logo='adobeacrobatreader'))
    a(badge('data', 'JSON · CSV · BibTeX', '13897a', 'Data: JSON, CSV and BibTeX', 'data/'))
    a(badge('version', J.VERSION, 'c95a22', f'Version {J.VERSION}', 'CHANGELOG.md'))
    a(badge('updated', J.fmt_date(s['cutoff']), '454c63', f'Updated {J.fmt_date(s["cutoff"])}'))
    a(badge('licence', 'MIT · CC BY 4.0', '737a8f', 'Code MIT, content CC BY 4.0', '#citation-and-licence'))
    a('  <a href="https://awesome.re"><img src="https://awesome.re/badge-flat2.svg" alt="Awesome"></a>')
    a('')
    authors = [x for x in cfg.get('authors') or [] if x.get('name')]
    if authors:
        a('  <p>' + ' · '.join(f'<a href="{J.safe_url(x.get("url"))}">{x["name"]}</a>' if J.safe_url(x.get('url')) else x['name'] for x in authors) + '</p>')
        affs = [x for x in cfg.get('affiliations') or [] if x]
        if affs:
            a('  <p><sub>' + ' &nbsp;·&nbsp; '.join(x if isinstance(x, str) else x.get('name', '') for x in affs) + '</sub></p>')
    a('</div>')
    a('')
    heading('About the survey')
    a('Jev is a hosted model from TypeSafe AI, released on 15 September 2026 as its first “System One” model. Software sends a text state and typed questions; '
      'the model answers from the declared options with probabilities and never writes free text. Open projects now copy its shape. This repository reads '
      'the studies of TypeSafe’s Jev and Jev-like typed decision models, audits the open resources and traces every number to its source.')
    a('')
    a('> [!IMPORTANT]')
    a('> **Four questions guide the survey.** **Meaning:** what do the probabilities mean? **Action:** when should software act on them? '
      '**Failure:** where do typed decisions fail? **Openness:** what do open implementations release?')
    a('')
    a('> [!NOTE]')
    a('> Numbers are as reported by paper authors, the vendor or repository maintainers. Nothing here is a unified leaderboard, and nothing was re-run.')
    a('')
    if site:
        a('**Explore:** ' + ' · '.join(f'[{t}]({site}#{k})' for k, t in (('map', 'Evidence map'), ('findings', 'Findings'), ('failures', 'Failure modes'),
                                                                        ('ecosystem', 'Open ecosystem'), ('literature', 'Literature search')))
          + ' · [Survey (PDF)](paper/main.pdf)')
        a('')
    slug = repo.rstrip('/').split('github.com/')[-1] if repo and 'github.com/' in repo else ''
    sections = ['Findings'] + [g for _, g in GROUPS] + ['Peripheral study', 'Open ecosystem', 'Background references', 'Related reviews and catalogues',
                                                        'Method', 'Contributing'] + (['Star history'] if slug else []) + ['Citation and licence']
    heading('Repository guide')
    a(' · '.join(f'[{h}](#{anchor(h)})' for h in sections))
    a('')
    a('## Choose a section')
    a('')
    a('Select a card to jump directly to its section.')
    a('')
    a('<p align="center">')
    for i, (key, title, sub) in enumerate(CARDS):
        if i == 3:
            a('  <br>')
        a(f'  <a href="#{anchor(title)}"><img src="assets/readme/card-{key}.svg" width="246" alt="{title}: {sub}"></a>')
    a('</p>')
    a('')
    a('## Reading the tables')
    a('')
    a('| Mark | Meaning |')
    a('| :-: | --- |')
    for mark, meaning in (('●', 'Available'), ('◐', 'Partially available'), ('◑', 'Restricted'), ('◔', 'Project page only'),
                          ('○', 'Not located — not the same as absent'), ('○ claimed', 'The paper says it is released, but no public release was found'),
                          ('–', 'Not applicable'), ('¹', 'Shares authors with other studies here; read together, not as independent replications')):
        a(f'| {mark} | {meaning} |')
    a('')
    a('---')
    a('')
    heading('Findings')
    a('Each finding is a synthesis across studies; open one to read it.')
    a('')
    for f in tax['findings']:
        a('<details>')
        a(f'<summary><b>{f["id"]} · {f["title"]}</b></summary>')
        a('')
        a(f['body'])
        a('')
        a('</details>')
        a('')
    for rel, title in GROUPS:
        ps = sorted([p for p in P if p['tier'] == 'core' and p['model_relationship'][0] == rel], key=lambda p: (p['published_at'], p['title']), reverse=True)
        if not ps:
            continue
        heading(title)
        a('| Date (v1) | Study | Headline (as reported) | Code |')
        a('| --- | --- | --- | :-: |')
        for p in ps:
            head = C[p['claims'][0]]['headline'] if p['claims'] else ''
            code = p['openness']['code']
            code_md = f'[{AVAIL_MD[code["status"]]}]({code["url"]})' if code.get('url') else AVAIL_MD[code['status']]
            fam = ' ¹' if p.get('study_family_id') else ''
            full = f'<br><sub>{md(p["title"])}</sub>' if p['title'] != p['short_title'] else ''
            a(f'| {p["published_at"][:10]} | **[{md(p["short_title"])}]({p["url"]})**{fam}{full} | {md(head)} | {code_md} |')
        a('')
    a('¹ Shares authors with other studies here; read together, not as independent replications. Code: ● available · ◐ partial · ◔ project page only · ○ not located · “claimed” = the paper says it is released but no public release was found.')
    a('')
    heading('Peripheral study')
    for p in [p for p in P if p['tier'] == 'peripheral']:
        a(f'- [{md(p["title"])}]({p["url"]}) — {md(p["relationship"])} {md(p["caveats"][0])}')
    a('')
    heading('Open ecosystem')
    a('Availability follows each project’s own README; nothing here was run. ● available · ◐ partial · ◑ restricted · ◔ project page only · ○ not located · – not applicable.')
    a('')
    by_role = defaultdict(list)
    for r in R:
        by_role[r['ecosystem']].append(r)
    fam_order = [f['id'] for f in tax['method_families']]
    a(f'### {T["ecosystem_roles"]["open_model"]["label"]}')
    a('')
    a('| Resource | Family | Base | Weights | Training | Evaluation | Data | Licence |')
    a('| --- | --- | --- | :-: | :-: | :-: | :-: | --- |')
    for r in sorted(by_role['open_model'], key=lambda r: (fam_order.index(r['method_family']) if r.get('method_family') else 99, r['full_name'].lower())):
        av = r.get('availability') or {}
        fam = T['method_families'][r['method_family']]['label'] if r.get('method_family') else '—'
        a(f'| [{r["full_name"]}]({r.get("readme_url") or r["url"]}) | {fam} | {md(r.get("base_model") or "—")} | '
          + ' | '.join(AVAIL_MD.get(av.get(k, 'not_assessed'), '·') for k in ('weights', 'training_code', 'evaluation', 'data')) + f' | {r.get("license") or "—"} |')
    a('')
    a(f'### {T["ecosystem_roles"]["benchmark"]["label"]}')
    a('')
    for r in sorted(by_role['benchmark'], key=lambda r: r['full_name'].lower()):
        a(f'- [{r["full_name"]}]({r["url"]}) — {md(r["summary"])} *{md(r["boundary"])}*')
    a('')
    a(f'### {T["ecosystem_roles"]["built_with"]["label"]}')
    a('')
    groups = defaultdict(list)
    for r in by_role['built_with']:
        groups[r.get('domain')].append(r)
    for app in tax['applications'] + [dict(id=None, label='Other')]:
        rs = sorted(groups.get(app['id'], []), key=lambda r: r['full_name'].lower())
        if not rs:
            continue
        a(f'**{app["label"]}**')
        a('')
        for r in rs:
            a(f'- [{r["full_name"]}]({r["url"]}) — {md(r["summary"])}')
        a('')
    a(f'### {T["ecosystem_roles"]["tooling"]["label"]}')
    a('')
    for r in sorted(by_role['tooling'], key=lambda r: (r['type'], r['full_name'].lower())):
        a(f'- [{r["full_name"]}]({r["url"]}) — {md(r["summary"])}')
    a('')
    heading('Background references')
    for g in tax['background_groups']:
        items = [p for p in P if p['tier'] == 'background' and p['background_group'] == g['id']]
        if not items:
            continue
        a(f'### {g["label"]}')
        a('')
        for p in sorted(items, key=lambda p: p['published_at'], reverse=True):
            venue = f' · {p["venue"]}' if p['venue_source'] in ('arxiv_comment', 'arxiv_journal_ref') else ''
            a(f'- [{md(p["title"])}]({p["url"]}) ({p["year"]}{venue}) — {md(p["role"])}')
        a('')
    heading('Related reviews and catalogues')
    for r in d['review-relations']['related_surveys']:
        a(f'- [{md(r.get("short") or r["title"])}]({r["url"]}) ({md(r.get("kind_label") or "")}) — {md(r.get("scope") or "")}.')
    a('')
    heading('Method')
    a('- Scope, search and screening: [docs/methodology.md](docs/methodology.md). Limitations: [docs/limitations.md](docs/limitations.md).')
    a('- How evidence records and openness fields are defined: [docs/evidence-audit.md](docs/evidence-audit.md).')
    a('- Survey manuscript: [PDF](paper/main.pdf) · [Markdown](paper/survey.md).')
    a('- Data: [`data/`](data/) (JSON records), [`data/exports/`](data/exports/) (CSV) and [`data/references.bib`](data/references.bib); screening lists in [`research/`](research/).')
    a('')
    heading('Contributing')
    a('New studies, corrections, code or weights updates and reproduction reports are welcome — see [CONTRIBUTING.md](CONTRIBUTING.md)'
      + (f' or [open an issue]({repo.rstrip("/")}/issues/new/choose).' if repo else '.'))
    a('')
    if repo:
        a(' · '.join(f'[{label}]({repo.rstrip("/")}/issues/new?template={form})' for form, label in ISSUE_FORMS))
        a('')
    if slug:
        heading('Star history')
        chart = f'https://api.star-history.com/svg?repos={slug}&type=Date'
        a('<p align="center">')
        a(f'  <a href="https://star-history.com/#{slug}&Date">')
        a('    <picture>')
        a(f'      <source media="(prefers-color-scheme: dark)" srcset="{chart}&theme=dark">')
        a(f'      <source media="(prefers-color-scheme: light)" srcset="{chart}">')
        a(f'      <img alt="Star history of {slug}" src="{chart}" width="800">')
        a('    </picture>')
        a('  </a>')
        a('</p>')
        a('')
    heading('Citation and licence')
    a('Citation metadata is in [CITATION.cff](CITATION.cff) (GitHub shows it under “Cite this repository”).')
    a('')
    if authors:
        first = authors[0]
        names = ' and '.join(f'{x.get("family_names") or x["name"]}, {x.get("given_names") or ""}'.rstrip(', ') for x in authors)
        key = (first.get('family_names') or first['name'].split()[-1]).lower() + s['cutoff'][:4] + 'jevsurvey'
        a('```bibtex')
        a(f'@misc{{{key},')
        a(f'  author       = {{{names}}},')
        a('  title        = {Jev and Typed Decision Models: An Empirical Survey of Calibration, Selective Control, and Open Implementations},')
        a(f'  year         = {{{s["cutoff"][:4]}}},')
        if site or repo:
            a(f'  howpublished = {{\\url{{{site or repo}}}}},')
        a(f'  note         = {{Version {J.VERSION}, updated {J.fmt_date(s["cutoff"])}. Working draft, not peer-reviewed}}')
        a('}')
        a('```')
        a('')
    a('Licences: the code (scripts, site, tests, workflows) is under the [MIT License](LICENSE); original text, figures and curated data are under '
      '[CC BY 4.0](LICENSE-CONTENT.md). Third-party material — paper metadata, quoted README facts, vendor documentation — keeps its own terms; '
      'see [NOTICE.md](NOTICE.md).')
    a('')
    (J.ROOT / 'README.md').write_text('\n'.join(L), encoding='utf-8')


if __name__ == '__main__':
    main()
